### ISSUE TITLE
Prevent excessive dice rolls/Limit amount of dice roll complexity

### ISSUE THREAD

**Issue by n1ru4l** [airjp73/dice-notation#14]
I wonder whether applying some dice roll limits such as disallowing rolling millions of dice with a single expression should be implemented within this library. Abusing this can potentially freeze a server that uses this library quite easily.

@airjp73 WHat are your thoughts on this?

**Comment by airjp73** [comment]
Yeah, I ran into this in my own project and limited the number of dice in-app. It probably does make sense to put this limit in the library itself since everyone using it will need this.

I opted for a max of 1 million dice and a maximum dice size of 1 million. I don't think anyone should need even close to that. Could probably make that the default and make it configurable.

**Comment by airjp73** [comment]
I guess the logic for this becomes tricky with custom dice rules. We can tell how many dice the default dice rule is going to roll, but that's not necessarily true for custom rolls.

**Comment by n1ru4l** [comment]
Couldnt we track the overall amount of random invocations and raise an error after invocation X. We could make the behaviour configurable. Actually this can be solved easily in user-land by providing a custom random function per dice roll operation 🤔

**Comment by airjp73** [comment]
That's worth considering. The way I did it was to iterate over the tokens and count how many dice were being rolled. I was thinking of adding a couple helpers to make it easier to do this.

**Comment by airjp73** [comment]
I spent some time going back and forth on this a bit, but I think building a limitation on the `random` function like you suggested makes sense. If the user tries to roll too many dice, it should throw an error so that we don't crash anything. I also want to be able to do other validations, but I think a separate API for that is more appropriate.
